// ============================================================
// Dashboard Data (AI edits this section)
// ============================================================

const userStoryRoles = ["Obsidianモバイルユーザー", "Zettelkasten実践者", "Obsidianユーザー"] as const satisfies readonly string[];

const scrum: ScrumDashboard = {
  product_goal: {
    statement: "Zettelkasten方式でアイデアを効率的に記録・整理し、知識のネットワークを構築できるようにする",
    success_metrics: [{ metric: "ノート作成の操作ステップ数", target: "3ステップ以内" }, { metric: "コマンド実行からノート作成完了まで", target: "5秒以内" }],
  },

  product_backlog: [
    // Phase 1-7: done (PBI-001〜016)
    { id: "PBI-001", story: { role: "Zettelkasten実践者", capability: "ノートタイプを識別できる", benefit: "分類・管理" }, acceptance_criteria: [{ criterion: "NoteType型+CONFIG", verification: "build" }], status: "done" },
    { id: "PBI-002", story: { role: "Zettelkasten実践者", capability: "フロントマターでメタデータ管理", benefit: "関係性追跡" }, acceptance_criteria: [{ criterion: "5メソッド", verification: "実装" }], status: "done" },
    { id: "PBI-003", story: { role: "Obsidianモバイルユーザー", capability: "選択テキストから新規ノート作成", benefit: "アイデア切り出し" }, acceptance_criteria: [{ criterion: "Modal+リンク置換", verification: "E2E" }], status: "done" },
    { id: "PBI-004", story: { role: "Obsidianモバイルユーザー", capability: "テンプレートでノート作成", benefit: "フォーマット管理" }, acceptance_criteria: [{ criterion: "変数展開", verification: "Templates存在" }], status: "done" },
    { id: "PBI-005", story: { role: "Obsidianモバイルユーザー", capability: "プラグイン設定カスタマイズ", benefit: "ワークフロー調整" }, acceptance_criteria: [{ criterion: "設定UI+永続化", verification: "保持確認" }], status: "done" },
    { id: "PBI-006", story: { role: "Zettelkasten実践者", capability: "ノート昇格", benefit: "段階的成熟" }, acceptance_criteria: [{ criterion: "PromotionService", verification: "昇格確認" }], status: "done" },
    { id: "PBI-007", story: { role: "Zettelkasten実践者", capability: "Permanent-Structure接続", benefit: "ネットワーク構築" }, acceptance_criteria: [{ criterion: "ConnectionManager", verification: "双方向リンク" }], status: "done" },
    { id: "PBI-008", story: { role: "Zettelkasten実践者", capability: "孤立Permanent発見", benefit: "接続漏れ防止" }, acceptance_criteria: [{ criterion: "OrphanView", verification: "リスト表示" }], status: "done" },
    { id: "PBI-009", story: { role: "Obsidianモバイルユーザー", capability: "ワンタップFleeting作成", benefit: "素早くキャプチャ" }, acceptance_criteria: [{ criterion: "QuickCaptureModal", verification: "E2E" }], status: "done" },
    { id: "PBI-010", story: { role: "Zettelkasten実践者", capability: "フォルダ自動生成", benefit: "手動作成不要" }, acceptance_criteria: [{ criterion: "initializeAllFolders", verification: "フォルダ存在" }], status: "done" },
    { id: "PBI-011", story: { role: "Zettelkasten実践者", capability: "接続率統計", benefit: "健全性把握" }, acceptance_criteria: [{ criterion: "getStats", verification: "UI表示" }], status: "done" },
    { id: "PBI-012", story: { role: "Zettelkasten実践者", capability: "フォルダサジェスト", benefit: "タイポ防止" }, acceptance_criteria: [{ criterion: "FolderSuggest", verification: "dropdown" }], status: "done" },
    { id: "PBI-013", story: { role: "Obsidianモバイルユーザー", capability: "コンテキストメニュー操作", benefit: "素早くアクセス" }, acceptance_criteria: [{ criterion: "editor-menu/file-menu", verification: "メニュー表示" }], status: "done" },
    { id: "PBI-014", story: { role: "Obsidianモバイルユーザー", capability: "i18n対応", benefit: "自然なUI" }, acceptance_criteria: [{ criterion: "t()関数+翻訳JSON", verification: "言語切替" }], status: "done" },
    { id: "PBI-015", story: { role: "Obsidianモバイルユーザー", capability: "メニューグルーピング", benefit: "操作性向上" }, acceptance_criteria: [{ criterion: "setSection", verification: "セパレーター" }], status: "done" },
    { id: "PBI-016", story: { role: "Obsidianユーザー", capability: "3ノートタイプ化", benefit: "シンプル化" }, acceptance_criteria: [{ criterion: "Structure/Index削除", verification: "grep+build" }], status: "done" },
    // Phase: 新設計リファクタリング (DESIGN.md準拠)
    { id: "PBI-017", story: { role: "Obsidianユーザー", capability: "設定画面で各ノートタイプのフォルダ・ファイル名形式・テンプレートを設定できる", benefit: "自分のワークフローに合わせたZettelkasten環境を構築できる" }, acceptance_criteria: [{ criterion: "NoteTypeSettings型定義(fileNameFormat/showAliasInput/templatePath/folder)", verification: "types/settings.ts" }, { criterion: "PageZettelSettings拡張+DEFAULT_SETTINGS", verification: "settings.ts" }, { criterion: "3ノートタイプ×設定UI(各4項目)", verification: "設定画面表示" }, { criterion: "設定永続化", verification: "data.json保存確認" }], status: "done" },
    { id: "PBI-018", story: { role: "Obsidianユーザー", capability: "NoteTypeSelectModalとAliasInputModalでノート作成フローを統一できる", benefit: "一貫したUI体験" }, acceptance_criteria: [{ criterion: "NoteTypeModal拡張: FuzzySuggestModal継承+3ノートタイプ表示(icon/label/description)+選択コールバック", verification: "既存note-type-modal.ts動作確認" }, { criterion: "AliasInputModal新規作成: Modal継承+テキスト入力+Enterキー対応+チェックボックス(Extract時のみ表示)+作成/キャンセルボタン", verification: "QuickCaptureModalパターン適用+DESIGN.md L65-77準拠" }, { criterion: "設定連動: showAliasInput=falseの場合AliasInputModalスキップ+ファイル名をデフォルトエイリアスとして使用", verification: "各ノートタイプ設定(fleeting/literature/permanent)のshowAliasInputフラグで表示制御" }, { criterion: "i18n対応: modals.aliasInput配下に翻訳キー追加(title/inputName/inputDesc/inputPlaceholder/removeIndent/createButton/cancelButton)", verification: "ja.json+en.json追加" }], status: "done" },
    { id: "PBI-019", story: { role: "Obsidianユーザー", capability: "TemplateServiceでプレースホルダーを展開", benefit: "一貫したフォーマット" }, acceptance_criteria: [{ criterion: "{{content}}展開: variables.content || \"\"をテンプレートに挿入", verification: "Extract時=選択範囲/Create時=空文字" }, { criterion: "{{date}}展開: YYYY-MM-DD固定形式で現在日付を挿入", verification: "moment().format(\"YYYY-MM-DD\")" }, { criterion: "{{time}}展開: HH:mm:ss固定形式で現在時刻を挿入", verification: "moment().format(\"HH:mm:ss\")" }, { criterion: "{{datetime}}展開: YYYY-MM-DD HH:mm:ss固定形式で現在日時を挿入", verification: "moment().format(\"YYYY-MM-DD HH:mm:ss\")" }, { criterion: "{{title}}展開: variables.titleをテンプレートに挿入", verification: "ファイル名（拡張子なし）" }, { criterion: "{{alias}}展開: variables.alias || \"\"をテンプレートに挿入", verification: "エイリアス入力時のみ値を持つ" }, { criterion: "{{date:FORMAT}}展開: 既存のカスタムフォーマット機能を維持", verification: "moment().format(FORMAT)" }, { criterion: "テンプレート未設定時のフォールバック: variables.content || \"\"を返す", verification: "loadTemplateがnull時" }], status: "done" },
    { id: "PBI-020", story: { role: "Obsidianユーザー", capability: "NoteCreatorServiceでノート作成統一", benefit: "コード重複防止" }, acceptance_criteria: [{ criterion: "NoteCreatorService実装: createNote(type,content,alias)メソッド+constructor(app,settings,folderService,templateService,frontmatterService)", verification: "services/note-creator-service.ts作成" }, { criterion: "ファイル名形式展開: settings[type].fileNameFormatをプレースホルダー展開({{date}}/{{time}}/{{datetime}}/{{zettel-id}}/{{title}})", verification: "generateFileName()メソッド実装" }, { criterion: "フォルダ配置: settings[type].folderから取得+folderService.ensureFolderExistsByPath()でフォルダ作成", verification: "NoteManager.createNote()のfolderService統合パターン踏襲" }, { criterion: "テンプレート統合: settings[type].templatePathから取得+templateService.getProcessedTemplate()でプレースホルダー展開(content/alias/title/date/time/datetime)", verification: "TemplateVariables{content,alias,title}を渡す" }, { criterion: "フロントマター統合: frontmatterService.addFrontmatter()でメタデータ追加", verification: "NoteManager.createNote()パターン踏襲" }, { criterion: "ファイル作成+Notice通知: app.vault.create()+new Notice()", verification: "NoteManager.createNote()パターン踏襲" }], status: "done" },
    { id: "PBI-021", story: { role: "Obsidianユーザー", capability: "Create New Noteコマンド", benefit: "素早く記録開始" }, acceptance_criteria: [{ criterion: "i18n翻訳キー追加: commands.createNewNote配下に日英翻訳キーを追加", verification: "i18n/locales/ja.json+en.json" }, { criterion: "コマンド登録: addCommand({id:\"create-new-note\",name:絵文字設定連動,callback})", verification: "main.ts+t(\"commands.createNewNote\")+settings.ui.showEmojiInCommands" }, { criterion: "NoteTypeModal表示: NoteTypeModal(app,onSelect,[\"fleeting\",\"literature\",\"permanent\"])", verification: "extract-selection-commandパターン踏襲" }, { criterion: "AliasInputModal表示: settings[type].showAliasInput=trueの場合のみ表示+showRemoveIndent=false", verification: "removeIndentチェックボックス非表示" }, { criterion: "NoteCreatorService統合: noteCreatorService.createNote(type,\"\",alias)+作成後openLinkText()でノートを開く", verification: "content=\"\"でテンプレートのみ展開+DESIGN.md L46準拠" }, { criterion: "main.tsにNoteCreatorService初期化: constructor(app,settings,folderService,templateService,frontmatterService)", verification: "既存サービス注入パターン踏襲" }], status: "done" },
    { id: "PBI-022", story: { role: "Obsidianユーザー", capability: "Extract to Note", benefit: "アトミックノート抽出" }, acceptance_criteria: [{ criterion: "NoteCreatorService統合: extract-selection-command.tsでnoteCreatorService.createNote(type,content,alias)を使用", verification: "NoteManager.createNote()からNoteCreatorService.createNote()に置換" }, { criterion: "マークダウンリンク置換: [[basename]]形式を[alias](relativePath)形式に変更", verification: "DESIGN.md L262-271準拠+エイリアスありは[alias](path)、なしは[filename](path)" }, { criterion: "Extract後のノートオープン設定: settings.behavior.openAfterExtract=trueの場合のみopenLinkText()実行", verification: "BehaviorSettings.openAfterExtract追加+条件分岐" }, { criterion: "インデント削除機能維持: 既存のremoveCommonIndent()とAliasInputModal.removeIndent統合確認", verification: "extract-selection-command.ts L117-134+AliasInputModal L65-73動作確認" }, { criterion: "i18n翻訳キー更新: commands.extractSelection → commands.extractToNote", verification: "ja.json+en.json+main.ts L58-64のコマンド名更新" }], status: "done" },
    { id: "PBI-023", story: { role: "Obsidianユーザー", capability: "孤立Permanent検出(リンクベース)", benefit: "ネットワーク統合" }, acceptance_criteria: [{ criterion: "マークダウンリンク検出", verification: "リンクベース" }, { criterion: "接続機能削除", verification: "ボタン非表示" }, { criterion: "ノートを開く", verification: "クリック遷移" }], status: "draft" },
    { id: "PBI-024", story: { role: "Obsidianユーザー", capability: "コンテキストメニューExtract", benefit: "右クリックアクセス" }, acceptance_criteria: [{ criterion: "メニュー表示", verification: "選択時のみ" }, { criterion: "コマンド実行", verification: "E2E" }, { criterion: "ON/OFF設定", verification: "設定連動" }], status: "draft" },
  ],

  sprint: null,

  definition_of_done: { checks: [{ name: "Build passes", run: "pnpm build" }, { name: "Lint passes", run: "pnpm lint" }, { name: "Format check passes", run: "pnpm format:check" }] },

  completed: [
    { number: 1, pbi_id: "PBI-001", goal: "NoteType型定義", status: "done", subtasks: [{ test: "型+定数", implementation: "types/note-types.ts", type: "behavioral", status: "completed", commits: [{ hash: "1eb7e33", message: "feat: NoteType system", phase: "green" }], notes: [] }] },
    { number: 2, pbi_id: "PBI-002", goal: "FrontmatterService", status: "done", subtasks: [{ test: "5メソッド", implementation: "services/frontmatter-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "0268c21", message: "feat: FrontmatterService", phase: "green" }], notes: [] }] },
    { number: 3, pbi_id: "PBI-003", goal: "選択テキスト→ノート", status: "done", subtasks: [{ test: "Command+Modal", implementation: "commands/,ui/modals/", type: "behavioral", status: "completed", commits: [{ hash: "527d854", message: "feat: ExtractSelection", phase: "green" }], notes: [] }] },
    { number: 4, pbi_id: "PBI-004", goal: "テンプレートノート作成", status: "done", subtasks: [{ test: "TemplateService", implementation: "services/template-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "275b08c", message: "feat: TemplateService", phase: "green" }], notes: [] }] },
    { number: 5, pbi_id: "PBI-005", goal: "設定タブUI実装", status: "done", subtasks: [{ test: "SettingTab+永続化", implementation: "settings.ts", type: "behavioral", status: "completed", commits: [{ hash: "34e5338", message: "feat: SettingTab", phase: "green" }], notes: [] }] },
    { number: 6, pbi_id: "PBI-006", goal: "ノート昇格機能", status: "done", subtasks: [{ test: "PromotionService+Command", implementation: "services/promotion-service.ts,commands/promote-note-command.ts", type: "behavioral", status: "completed", commits: [{ hash: "ca4d202", message: "feat: PromotionService", phase: "green" }, { hash: "7ee7498", message: "feat: PromoteNoteCommand", phase: "green" }], notes: [] }] },
    { number: 7, pbi_id: "PBI-007", goal: "Permanent-Structure接続", status: "done", subtasks: [{ test: "ConnectionManager+LinkCommand", implementation: "core/connection-manager.ts,commands/link-permanent-command.ts", type: "behavioral", status: "completed", commits: [{ hash: "67af70b", message: "feat: ConnectionManager", phase: "green" }, { hash: "fb76382", message: "feat: LinkPermanentCommand", phase: "green" }], notes: [] }] },
    { number: 8, pbi_id: "PBI-008", goal: "孤立Permanent発見", status: "done", subtasks: [{ test: "OrphanDetector+View", implementation: "services/orphan-detector-service.ts,ui/views/orphan-view.ts", type: "behavioral", status: "completed", commits: [{ hash: "af1660f", message: "feat: OrphanDetectorService", phase: "green" }, { hash: "b775960", message: "feat: OrphanView", phase: "green" }], notes: [] }] },
    { number: 9, pbi_id: "PBI-011", goal: "接続率統計表示", status: "done", subtasks: [{ test: "getStats+UI", implementation: "services/orphan-detector-service.ts,ui/views/orphan-view.ts", type: "behavioral", status: "completed", commits: [{ hash: "151f9ac", message: "feat: getStats()", phase: "green" }], notes: [] }] },
    { number: 10, pbi_id: "PBI-009", goal: "ワンタップFleeting", status: "done", subtasks: [{ test: "QuickCaptureModal+コマンド", implementation: "ui/modals/quick-capture-modal.ts,main.ts", type: "behavioral", status: "completed", commits: [{ hash: "3df2861", message: "feat: QuickCaptureModal", phase: "green" }], notes: [] }] },
    { number: 11, pbi_id: "PBI-010", goal: "フォルダ自動生成", status: "done", subtasks: [{ test: "initializeAllFolders", implementation: "services/folder-service.ts,main.ts", type: "behavioral", status: "completed", commits: [{ hash: "6562f6c", message: "feat: auto folder init", phase: "green" }], notes: [] }] },
    { number: 12, pbi_id: "PBI-012", goal: "FolderSuggest", status: "done", subtasks: [{ test: "AbstractInputSuggest継承", implementation: "ui/suggesters/folder-suggest.ts,settings.ts", type: "behavioral", status: "completed", commits: [{ hash: "2c1069c", message: "feat: FolderSuggest", phase: "green" }], notes: [] }] },
    { number: 13, pbi_id: "PBI-013", goal: "コンテキストメニュー", status: "done", subtasks: [{ test: "editor-menu/file-menu", implementation: "main.ts,settings.ts", type: "behavioral", status: "completed", commits: [{ hash: "31a755d", message: "feat: context menu", phase: "green" }], notes: [] }] },
    { number: 14, pbi_id: "PBI-015", goal: "メニューグルーピング", status: "done", subtasks: [{ test: "setSection+addSeparator", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "8df2157", message: "feat: menu grouping", phase: "green" }], notes: [] }] },
    { number: 15, pbi_id: "PBI-014", goal: "i18n国際化", status: "done", subtasks: [{ test: "t()+翻訳JSON", implementation: "i18n/,main.ts,settings.ts", type: "behavioral", status: "completed", commits: [{ hash: "65d7639", message: "feat: i18n", phase: "green" }], notes: [] }] },
    { number: 16, pbi_id: "PBI-016", goal: "3ノートタイプ化", status: "done", subtasks: [{ test: "Structure/Index削除", implementation: "4ファイル削除+10ファイル更新", type: "structural", status: "completed", commits: [{ hash: "f72e1d8", message: "refactor: remove Structure files", phase: "green" }, { hash: "c26fa4a", message: "refactor: fix build", phase: "green" }], notes: [] }] },
    { number: 17, pbi_id: "PBI-017", goal: "ノートタイプ別設定機能", status: "done", subtasks: [{ test: "NoteTypeSettings型+PageZettelSettings拡張+3ノートタイプUI+永続化", implementation: "types/settings.ts,settings.ts", type: "behavioral", status: "completed", commits: [{ hash: "6d046a7", message: "feat: NoteTypeSettings", phase: "green" }, { hash: "5d70f14", message: "feat: settings UI", phase: "green" }], notes: [] }] },
    { number: 18, pbi_id: "PBI-018", goal: "ノート作成フローの統一UI実装", status: "done", subtasks: [{ test: "i18n翻訳キー", implementation: "i18n/locales/", type: "behavioral", status: "completed", commits: [{ hash: "f3a6552", message: "feat(i18n): add aliasInput modal translation keys", phase: "green" }], notes: [] }, { test: "AliasInputModal基本+チェックボックス", implementation: "ui/modals/alias-input-modal.ts", type: "behavioral", status: "completed", commits: [{ hash: "8a2abb6", message: "feat(ui): implement AliasInputModal basic structure", phase: "green" }, { hash: "7760064", message: "feat(ui): add removeIndent checkbox to AliasInputModal", phase: "green" }], notes: [] }, { test: "NoteTypeModal動作確認", implementation: "ui/modals/note-type-modal.ts", type: "behavioral", status: "completed", commits: [{ hash: "16a80a6", message: "docs(ui): verify NoteTypeModal meets AC1 requirements", phase: "green" }], notes: [] }, { test: "設定連動", implementation: "commands/extract-selection-command.ts", type: "behavioral", status: "completed", commits: [{ hash: "42f39f4", message: "feat(commands): integrate AliasInputModal with settings", phase: "green" }], notes: [] }] },
    { number: 19, pbi_id: "PBI-019", goal: "テンプレートプレースホルダー展開機能の完成", status: "done", subtasks: [{ test: "{{date}}/{{time}}/{{datetime}}固定形式展開", implementation: "services/template-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "214a77b", message: "feat(template): add fixed format date/time/datetime placeholders", phase: "green" }], notes: ["AC2: {{date}}をYYYY-MM-DD形式で展開", "AC3: {{time}}をHH:mm:ss形式で展開", "AC4: {{datetime}}をYYYY-MM-DD HH:mm:ss形式で展開", "既存の{{date:FORMAT}}と統合性確認"] }, { test: "TemplateVariables型拡張（alias追加）", implementation: "services/template-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "5eccb0b", message: "feat(template): extend TemplateVariables with alias field", phase: "green" }], notes: ["TemplateVariablesインターフェースにalias?: stringを追加", "型定義のみのため即座にGreen"] }, { test: "{{alias}}展開: variables.alias || \"\"", implementation: "services/template-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "a053600", message: "feat(template): add {{alias}} placeholder expansion", phase: "green" }], notes: ["AC6: variables.alias || \"\"で展開", "エイリアス入力時のみ値を持つ"] }, { test: "既存機能統合検証（{{content}}/{{date:FORMAT}}/フォールバック）", implementation: "services/template-service.ts", type: "behavioral", status: "completed", commits: [], notes: ["AC1: {{content}}展開が正常動作（Line 74）", "AC5: {{title}}展開が正常動作（Line 71）", "AC7: {{date:FORMAT}}カスタムフォーマット維持（Line 80-86）", "AC8: テンプレート未設定時のフォールバック確認（Line 30-31）", "Definition of Done（build/lint/format）全てパス"] }] },
    { number: 20, pbi_id: "PBI-020", goal: "ノート作成サービスの統一実装", status: "done", subtasks: [{ test: "NoteCreatorService基本構造", implementation: "services/note-creator-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "c7a7456", message: "feat(services): add NoteCreatorService basic structure", phase: "green" }], notes: ["AC1: constructor(app,settings,folderService,templateService,frontmatterService)", "依存サービスの注入パターン適用", "NoteManager.createNote()パターン踏襲"] }, { test: "ファイル名形式展開", implementation: "services/note-creator-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "d30576c", message: "feat(services): add generateFileName method with placeholder expansion", phase: "green" }], notes: ["AC2: settings[type].fileNameFormatをプレースホルダー展開", "{{date}}/{{time}}/{{datetime}}/{{zettel-id}}/{{title}}/{{alias}}全対応"] }, { test: "フォルダ配置+テンプレート+フロントマター+ファイル作成統合", implementation: "services/note-creator-service.ts", type: "behavioral", status: "completed", commits: [{ hash: "3f2430b", message: "feat(services): add folder placement with ensureFolderExistsByPath", phase: "green" }], notes: ["AC3: ensureFolderExistsByPath()でフォルダ作成", "AC4: templateService.getProcessedTemplate()でテンプレート展開", "AC5: frontmatterService.addFrontmatter()でメタデータ追加", "AC6: app.vault.create() + new Notice()でファイル作成+通知", "createNote()メソッドで全機能統合完了"] }] },
    { number: 21, pbi_id: "PBI-021", goal: "Create New Noteコマンドの実装", status: "done", subtasks: [{ test: "i18n翻訳キー追加: commands.createNewNote配下に日英翻訳キー追加", implementation: "i18n/locales/ja.json, i18n/locales/en.json", type: "behavioral", status: "completed", commits: [{ hash: "3539430", message: "feat(i18n): add createNewNote command translation keys", phase: "green" }], notes: ["AC1対応", "Sprint 18のi18n実装パターン踏襲"] }, { test: "NoteCreatorService初期化: main.ts内でNoteCreatorService初期化（app, settings, folderService, templateService, frontmatterService注入）", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "a7a2bc7", message: "feat(services): initialize NoteCreatorService in main.ts", phase: "green" }], notes: ["AC6対応", "既存サービス注入パターン踏襲（Sprint 20参照）"] }, { test: "コマンド登録基本構造: addCommand({id:\"create-new-note\", name:絵文字設定連動, callback})", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "d0b4026", message: "feat(commands): add create-new-note command registration", phase: "green" }], notes: ["AC2対応", "settings.ui.showEmojiInCommandsフラグでアイコン表示制御"] }, { test: "NoteTypeModal表示統合: NoteTypeModal(app, onSelect, [\"fleeting\", \"literature\", \"permanent\"])呼び出し", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "861cc61", message: "feat(commands): integrate NoteTypeModal in create-new-note", phase: "green" }], notes: ["AC3対応", "extract-selection-commandパターン踏襲"] }, { test: "AliasInputModal条件表示: settings[type].showAliasInput=trueの場合のみAliasInputModal表示 + showRemoveIndent=false", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "b62c10e", message: "feat(commands): complete create-new-note command implementation", phase: "green" }], notes: ["AC4対応", "removeIndentチェックボックス非表示"] }, { test: "NoteCreatorService統合 + ノートオープン: noteCreatorService.createNote(type, \"\", alias) + openLinkText()でノートを開く", implementation: "main.ts", type: "behavioral", status: "completed", commits: [{ hash: "b62c10e", message: "feat(commands): complete create-new-note command implementation", phase: "green" }], notes: ["AC5対応", "content=\"\"でテンプレートのみ展開", "DESIGN.md L46準拠"] }] },
    { number: 22, pbi_id: "PBI-022", goal: "Extract to Note機能の新設計準拠実装", status: "done", subtasks: [{ test: "AC1+AC4: NoteCreatorService統合+インデント削除機能維持", implementation: "commands/extract-selection-command.ts", type: "behavioral", status: "completed", commits: [{ hash: "39a7b11", message: "refactor(commands): integrate NoteCreatorService in extract-selection", phase: "green" }], notes: ["NoteManager.createNote() → noteCreatorService.createNote()に置換", "removeCommonIndent()関数維持確認（L111-129）", "AliasInputModal.removeIndent統合確認（L61-62）"] }, { test: "AC3-1: BehaviorSettings.openAfterExtract設定追加", implementation: "types/settings.ts, settings.ts, i18n/locales/", type: "behavioral", status: "completed", commits: [{ hash: "ae9adab", message: "feat(settings): add openAfterExtract behavior setting", phase: "green" }], notes: ["BehaviorSettings型にopenAfterExtract: boolean追加", "DEFAULT_SETTINGS.behavior.openAfterExtract = true追加", "設定UI追加（insertLinkAfterExtractと同じパターン）", "i18n翻訳キー追加（ja.json + en.json）"] }, { test: "AC3-2+AC2+AC5: 設定連動ノートオープン+マークダウンリンク形式+i18n更新", implementation: "commands/extract-selection-command.ts, main.ts, i18n/locales/", type: "behavioral", status: "completed", commits: [{ hash: "d56063e", message: "feat(commands): enhance extract-to-note with markdown links and i18n", phase: "green" }], notes: ["AC3-2: openAfterExtract=trueの場合のみopenLinkText()実行（L103）", "AC2: [[basename]] → [alias](relativePath)形式（DESIGN.md L262-271準拠）", "AC5: commands.extractSelection → commands.extractToNote（ja/en翻訳キー更新）"] }] },
  ],

  retrospectives: [
    { sprint: 1, improvements: [{ action: "DoD検証", timing: "sprint", status: "completed", outcome: "Sprint2適用" }] },
    { sprint: 2, improvements: [{ action: "サブタスク小分割", timing: "sprint", status: "completed", outcome: "Sprint3適用" }] },
    { sprint: 3, improvements: [{ action: "サブタスク=コミット単位", timing: "sprint", status: "completed", outcome: "Sprint4確認" }] },
    { sprint: 4, improvements: [{ action: "AC-実装整合性確認", timing: "sprint", status: "completed", outcome: "Sprint5確認" }] },
    { sprint: 5, improvements: [{ action: "1AC=1論理グループ", timing: "sprint", status: "completed", outcome: "Sprint6達成" }] },
    { sprint: 6, improvements: [{ action: "AC依存関係順", timing: "sprint", status: "completed", outcome: "Sprint7成功" }] },
    { sprint: 7, improvements: [{ action: "既存実装検索必須化", timing: "sprint", status: "completed", outcome: "Sprint8/9確立" }] },
    { sprint: 8, improvements: [{ action: "メンテナンスPBI候補作成", timing: "product", status: "active", outcome: null }] },
    { sprint: 9, improvements: [{ action: "既存実装拡張パターン継続", timing: "sprint", status: "completed", outcome: "getStats+UI統合成功" }] },
    { sprint: 10, improvements: [{ action: "Modal実装前に既存Modal調査必須化", timing: "sprint", status: "completed", outcome: "Sprint11でModal不使用" }] },
    { sprint: 11, improvements: [{ action: "既存Service活用を実装前調査で確認", timing: "sprint", status: "completed", outcome: "Sprint12でAbstractInputSuggest活用" }] },
    { sprint: 12, improvements: [{ action: "Obsidian API継承パターン活用継続", timing: "sprint", status: "completed", outcome: "Sprint13でworkspace events適用" }] },
    { sprint: 13, improvements: [{ action: "型定義事前確認継続", timing: "sprint", status: "completed", outcome: "Sprint14でsetSection採用" }] },
    { sprint: 14, improvements: [{ action: "obsidian.d.ts確認必須化", timing: "sprint", status: "completed", outcome: "Sprint15でgetLanguage活用" }] },
    { sprint: 15, improvements: [{ action: "tsconfig.json更新確認", timing: "sprint", status: "active", outcome: null }] },
    { sprint: 16, improvements: [{ action: "大規模削除時grep網羅性向上", timing: "sprint", status: "active", outcome: null }, { action: "型依存関係の明示的リストアップ", timing: "sprint", status: "completed", outcome: "PBI-017で適用: NoteTypeSettings型→PageZettelSettings拡張→UI実装→永続化検証の順で進行、コンパイルエラーなし" }] },
    { sprint: 17, improvements: [{ action: "設定UI共通コンポーネント抽出パターン確立", timing: "sprint", status: "active", outcome: null }, { action: "UI実装前のi18n翻訳キー事前設計", timing: "sprint", status: "completed", outcome: "Sprint18でi18n翻訳キーを最初に実装し、Modal実装時にキー参照可能" }] },
    { sprint: 18, improvements: [{ action: "Modal実装時の既存パターン完全踏襲", timing: "sprint", status: "completed", outcome: "QuickCaptureModalパターンを完全踏襲してAliasInputModal実装成功。既存NoteTypeModal確認により不要な実装回避" }, { action: "設定連動機能の段階的統合検証", timing: "sprint", status: "completed", outcome: "showAliasInputフラグによるModal表示制御成功。Sprint19でテンプレート展開機能統合完了" }] },
    { sprint: 19, improvements: [{ action: "既存Service拡張パターン継続（TemplateService）", timing: "sprint", status: "completed", outcome: "既存のTemplateServiceを拡張し、8つのプレースホルダー展開機能を追加。既存の{{date:FORMAT}}を壊さずに固定形式{{date}}/{{time}}/{{datetime}}を共存実装" }, { action: "正規表現マッチ順序による機能共存", timing: "sprint", status: "completed", outcome: "{{date:FORMAT}}を先にマッチさせることで、{{date}}との衝突を回避。段階的な機能追加が成功" }, { action: "型拡張による型安全性維持", timing: "sprint", status: "completed", outcome: "TemplateVariablesにalias?:stringを追加し、既存コードを壊さずに型安全に機能拡張" }] },
    { sprint: 20, improvements: [{ action: "統合Serviceパターン確立（NoteCreatorService）", timing: "sprint", status: "completed", outcome: "複数サービス（FolderService/TemplateService/FrontmatterService）を統合し、ノート作成を一元管理。依存性注入パターンで既存サービスを再利用" }, { action: "プレースホルダー展開の統一実装", timing: "sprint", status: "completed", outcome: "ファイル名形式で{{date}}/{{time}}/{{datetime}}/{{zettel-id}}/{{title}}/{{alias}}を完全サポート。TemplateServiceと同じプレースホルダーパターンを踏襲" }, { action: "createNote()での機能統合戦略", timing: "sprint", status: "completed", outcome: "複数ACをcreateNote()メソッド内で統合実装。単一コミットで関連機能をまとめて実装することでテスト可能な単位を維持" }] },
    { sprint: 21, improvements: [{ action: "基盤先行・統合後行の段階的実装アプローチ継続", timing: "sprint", status: "completed", outcome: "Sprint 18-20で作成した基盤（NoteTypeModal/AliasInputModal/NoteCreatorService）を効果的に再利用し、Create New Noteコマンドを迅速に実装完了" }, { action: "i18n翻訳キー事前追加パターン継続", timing: "sprint", status: "completed", outcome: "Sprint 18で確立したパターンを継続。コマンド実装時にi18n翻訳キーが既に存在しているため、キー参照が容易で実装がスムーズ" }, { action: "再利用可能なメソッド設計（createNoteAndOpen）", timing: "sprint", status: "completed", outcome: "createNoteAndOpen()メソッドをNoteCreatorServiceに切り出すことで、今後のExtract to Note（PBI-022）でも再利用可能な設計を実現" }, { action: "設定連動による一貫したUX維持", timing: "sprint", status: "completed", outcome: "showEmojiInCommands設定フラグで絵文字表示を制御し、全コマンドで一貫したUX体験を提供" }] },
    { sprint: 22, improvements: [{ action: "NoteCreatorService統合による既存コード置換パターン確立", timing: "sprint", status: "completed", outcome: "Sprint 20で作成したNoteCreatorServiceをExtract to Note機能に統合。NoteManager.createNote()を完全に置換し、新設計への移行を完了" }, { action: "マークダウンリンク形式への統一（WikiリンクからMarkdownリンクへ）", timing: "sprint", status: "completed", outcome: "[[basename]]形式から[alias](relativePath)形式に変更。エイリアス表示とファイル名表示を統一し、DESIGN.md L262-271準拠を実現" }, { action: "BehaviorSettings拡張による設定オプション追加パターン継続", timing: "sprint", status: "completed", outcome: "openAfterExtract設定を追加し、Extract後のノートオープン動作を制御可能に。insertLinkAfterExtractと同様のパターンで実装" }, { action: "既存機能維持の検証手法確立（removeCommonIndent）", timing: "sprint", status: "completed", outcome: "既存のremoveCommonIndent()関数とAliasInputModal.removeIndent統合を確認。リファクタリング時も機能が維持されることを検証" }, { action: "i18n翻訳キー更新による命名規則統一", timing: "sprint", status: "completed", outcome: "commands.extractSelection → commands.extractToNoteに更新。コマンド名とi18n翻訳キーの命名規則を統一し、保守性を向上" }] },
  ],
};

// ============================================================
// Type Definitions (DO NOT MODIFY)
// ============================================================
type PBIStatus = "draft" | "refining" | "ready" | "done";
type SprintStatus = "planning" | "in_progress" | "review" | "done" | "cancelled";
type SubtaskStatus = "pending" | "red" | "green" | "refactoring" | "completed";
type SubtaskType = "behavioral" | "structural";
type CommitPhase = "green" | "refactoring";
type ImprovementTiming = "immediate" | "sprint" | "product";
type ImprovementStatus = "active" | "completed" | "abandoned";
interface SuccessMetric { metric: string; target: string; }
interface ProductGoal { statement: string; success_metrics: SuccessMetric[]; }
interface AcceptanceCriterion { criterion: string; verification: string; }
interface UserStory { role: (typeof userStoryRoles)[number]; capability: string; benefit: string; }
interface PBI { id: string; story: UserStory; acceptance_criteria: AcceptanceCriterion[]; status: PBIStatus; }
interface Commit { hash: string; message: string; phase: CommitPhase; }
interface Subtask { test: string; implementation: string; type: SubtaskType; status: SubtaskStatus; commits: Commit[]; notes: string[]; }
interface Sprint { number: number; pbi_id: string; goal: string; status: SprintStatus; subtasks: Subtask[]; }
interface DoDCheck { name: string; run: string; }
interface DefinitionOfDone { checks: DoDCheck[]; }
interface Improvement { action: string; timing: ImprovementTiming; status: ImprovementStatus; outcome: string | null; }
interface Retrospective { sprint: number; improvements: Improvement[]; }
interface ScrumDashboard { product_goal: ProductGoal; product_backlog: PBI[]; sprint: Sprint | null; definition_of_done: DefinitionOfDone; completed: Sprint[]; retrospectives: Retrospective[]; }

console.log(JSON.stringify(scrum, null, 2));
