import { parseYaml } from "obsidian";
import type { NoteMetadata, NoteType } from "../types/note-types";

/**
 * テンプレートのパース結果
 */
export interface ParsedTemplate {
	frontmatter: Record<string, unknown> | null;
	body: string;
}

/**
 * テンプレート文字列からフロントマターと本文を分離
 * @param content テンプレート全文
 * @returns フロントマターオブジェクトと本文
 */
export function parseTemplateFrontmatter(content: string): ParsedTemplate {
	// YAMLフロントマター正規表現: ^---\n ... \n---
	const frontmatterRegex = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
	const match = content.match(frontmatterRegex);

	if (!match || match[1] === undefined) {
		return { frontmatter: null, body: content };
	}

	const yamlContent = match[1];
	const body = content.slice(match[0].length);

	try {
		const parsed = parseYaml(yamlContent) as Record<string, unknown>;
		return { frontmatter: parsed, body };
	} catch {
		// パースエラー時はフロントマターなしとして扱う
		return { frontmatter: null, body: content };
	}
}

/**
 * デフォルトフロントマターとテンプレートフロントマターをマージ
 * - type フィールドは常にデフォルト値を使用（テンプレートでの上書き不可）
 * - その他のフィールドはテンプレート優先
 *
 * @param defaultMetadata デフォルトのメタデータ（NoteCreatorService が生成）
 * @param templateFrontmatter テンプレートから抽出したフロントマター
 * @returns マージ済みのメタデータ
 */
export function mergeFrontmatter(
	defaultMetadata: NoteMetadata,
	templateFrontmatter: Record<string, unknown> | null,
): NoteMetadata {
	if (!templateFrontmatter) {
		return defaultMetadata;
	}

	// typeフィールドを除外してマージ（テンプレートのtypeは無視）
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	const { type: _ignoredType, ...templateRest } = templateFrontmatter;

	return {
		...defaultMetadata, // デフォルト値をベースに
		...templateRest, // テンプレートのフィールドで上書き
		type: defaultMetadata.type, // typeは必ずデフォルト値
	} as NoteMetadata;
}

/**
 * デフォルトフロントマターのプレビュー文字列を生成
 * @param type ノートタイプ
 * @returns プレビュー用のYAML文字列
 */
export function getDefaultFrontmatterPreview(type: NoteType): string {
	const lines = [
		"---",
		`type: ${type}`,
		"created: <auto-generated>",
		"tags:",
		`  - ${type}`,
		"---",
	];
	return lines.join("\n");
}
